import type { ServiceWorkflow } from '@/types/wizard'

export const ajusteDeEstatusWorkflow: ServiceWorkflow = {
  slug: 'ajuste-de-estatus',
  name: 'Ajuste de Estatus (I-485)',
  steps: [
    {
      step: 1,
      title: 'Información Personal',
      description: 'Datos personales del solicitante para el formulario I-485',
      type: 'form',
      fields: [
        { key: 'legal_last_name', label: 'Apellido legal', type: 'text', required: true },
        { key: 'legal_first_name', label: 'Nombre legal', type: 'text', required: true },
        { key: 'legal_middle_name', label: 'Segundo nombre', type: 'text' },
        {
          key: 'other_names',
          label: 'Otros nombres usados',
          type: 'text_array',
          helper: 'Incluya nombres de soltera, alias, o cualquier otro nombre',
        },
        { key: 'date_of_birth', label: 'Fecha de nacimiento', type: 'date', required: true },
        { key: 'city_of_birth', label: 'Ciudad de nacimiento', type: 'text', required: true },
        { key: 'country_of_birth', label: 'País de nacimiento', type: 'country_select', required: true },
        { key: 'nationality', label: 'Nacionalidad', type: 'country_select', required: true },
        {
          key: 'gender',
          label: 'Sexo',
          type: 'select',
          options: ['Masculino', 'Femenino'],
          required: true,
        },
        {
          key: 'marital_status',
          label: 'Estado civil',
          type: 'select',
          options: ['Soltero/a', 'Casado/a', 'Divorciado/a', 'Viudo/a'],
          required: true,
        },
        { key: 'ssn', label: 'Número de Seguro Social (SSN)', type: 'text' },
        {
          key: 'a_number',
          label: 'Número A (Alien Number)',
          type: 'text',
          helper: "Comienza con 'A' seguido de 8 o 9 dígitos",
        },
        { key: 'uscis_account', label: 'Número de cuenta USCIS en línea', type: 'text' },
        { key: 'residence_address_street', label: 'Dirección de residencia (calle)', type: 'text', required: true },
        { key: 'residence_address_city', label: 'Ciudad', type: 'text', required: true },
        { key: 'residence_address_state', label: 'Estado', type: 'us_state_select', required: true },
        { key: 'residence_address_zip', label: 'Código postal', type: 'text', required: true },
        { key: 'phone', label: 'Teléfono', type: 'phone', required: true },
        { key: 'email', label: 'Correo electrónico', type: 'email' },
        {
          key: 'mailing_same_as_residence',
          label: '¿La dirección postal es la misma que la de residencia?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'mailing_address',
          label: 'Dirección postal',
          type: 'address_group',
          conditional: 'mailing_same_as_residence === false',
        },
        { key: 'race_ethnicity', label: 'Raza / Etnicidad', type: 'text' },
        { key: 'height_feet', label: 'Estatura (pies)', type: 'number' },
        { key: 'height_inches', label: 'Estatura (pulgadas)', type: 'number' },
        { key: 'weight_lbs', label: 'Peso (libras)', type: 'number' },
        {
          key: 'eye_color',
          label: 'Color de ojos',
          type: 'select',
          options: ['Negro', 'Café', 'Azul', 'Verde', 'Avellana', 'Gris', 'Otro'],
        },
        {
          key: 'hair_color',
          label: 'Color de cabello',
          type: 'select',
          options: ['Negro', 'Café', 'Rubio', 'Rojo', 'Gris', 'Blanco', 'Calvo', 'Otro'],
        },
      ],
    },
    {
      step: 2,
      title: 'Información de Inmigración',
      description: 'Historial migratorio en EE.UU. y datos de entrada',
      type: 'form',
      fields: [
        {
          key: 'last_entry_date',
          label: 'Fecha de última entrada a EE.UU.',
          type: 'date',
          required: true,
        },
        {
          key: 'entry_place',
          label: 'Lugar de última entrada',
          type: 'text',
          required: true,
        },
        {
          key: 'entry_status',
          label: 'Estatus de admisión',
          type: 'select',
          options: [
            'Visa de turista (B-1/B-2)',
            'Visa de estudiante (F-1)',
            'Visa de trabajo (H-1B)',
            'Visa de prometido/a (K-1)',
            'Parole',
            'Sin inspección',
            'TPS',
            'Otro',
          ],
          required: true,
        },
        {
          key: 'entry_status_other',
          label: 'Especifique otro estatus',
          type: 'text',
          conditional: "entry_status === 'Otro'",
        },
        { key: 'i94_number', label: 'Número I-94', type: 'text' },
        {
          key: 'current_immigration_status',
          label: 'Estatus migratorio actual',
          type: 'text',
          required: true,
          helper: 'Ej: B-2, F-1, H-1B, parolee, sin estatus, TPS, etc.',
        },
        { key: 'status_expires', label: 'Fecha de expiración del estatus', type: 'date' },
        { key: 'passport_number', label: 'Número de pasaporte', type: 'text', required: true },
        { key: 'passport_country', label: 'País del pasaporte', type: 'country_select', required: true },
        { key: 'passport_expiry', label: 'Fecha de expiración del pasaporte', type: 'date', required: true },
        {
          key: 'in_removal_proceedings',
          label: '¿Está o ha estado en proceso de deportación?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'removal_details',
          label: 'Detalles de proceso de deportación',
          type: 'long_text',
          conditional: 'in_removal_proceedings === true',
        },
        {
          key: 'previous_applications',
          label: '¿Ha presentado solicitudes anteriores a USCIS?',
          type: 'boolean',
        },
        {
          key: 'previous_applications_details',
          label: 'Detalles de solicitudes anteriores',
          type: 'long_text',
          conditional: 'previous_applications === true',
          helper: 'Incluya tipo de solicitud, fecha, y resultado',
        },
        {
          key: 'entries_to_us',
          label: 'Historial de entradas a EE.UU.',
          type: 'repeatable_group',
          helper: 'Liste todas las veces que ha entrado a EE.UU.',
          subfields: [
            { key: 'entry_date', label: 'Fecha de entrada', type: 'date' },
            { key: 'entry_location', label: 'Lugar de entrada', type: 'text' },
            { key: 'entry_visa_status', label: 'Estatus de entrada', type: 'text' },
            { key: 'departure_date', label: 'Fecha de salida', type: 'date' },
          ],
        },
      ],
    },
    {
      step: 3,
      title: 'Información del Peticionario / Patrocinador',
      description: 'Datos de la persona o entidad que presentó la petición (si aplica)',
      type: 'form',
      fields: [
        {
          key: 'basis_for_adjustment',
          label: 'Base para el ajuste de estatus',
          type: 'select',
          options: [
            'Familiar inmediato de ciudadano (IR)',
            'Preferencia familiar (F1, F2, F3, F4)',
            'Basado en empleo (EB)',
            'Asilo concedido',
            'Lotería de visas (DV)',
            'VAWA (Violencia doméstica)',
            'Visa U (víctima de crimen)',
            'Visa T (víctima de tráfico)',
            'Registro (residencia continua desde antes de 1972)',
            'Acto legislativo especial',
            'Otro',
          ],
          required: true,
        },
        {
          key: 'basis_other',
          label: 'Especifique otra base',
          type: 'text',
          conditional: "basis_for_adjustment === 'Otro'",
        },
        {
          key: 'has_approved_petition',
          label: '¿Tiene una petición aprobada (I-130, I-140, etc.)?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'petition_type',
          label: 'Tipo de petición',
          type: 'select',
          options: ['I-130 (Familiar)', 'I-140 (Empleo)', 'I-360 (Especial)', 'Otro'],
          conditional: 'has_approved_petition === true',
        },
        {
          key: 'petition_receipt_number',
          label: 'Número de recibo de la petición',
          type: 'text',
          conditional: 'has_approved_petition === true',
        },
        {
          key: 'priority_date',
          label: 'Fecha de prioridad',
          type: 'date',
          conditional: 'has_approved_petition === true',
          helper: 'Fecha en que se presentó la petición original',
        },
        {
          key: 'petitioner_last_name',
          label: 'Apellido del peticionario',
          type: 'text',
        },
        {
          key: 'petitioner_first_name',
          label: 'Nombre del peticionario',
          type: 'text',
        },
        {
          key: 'petitioner_relationship',
          label: 'Relación con el peticionario',
          type: 'select',
          options: ['Cónyuge', 'Padre/Madre', 'Hijo/a', 'Hermano/a', 'Empleador', 'Otro'],
        },
        {
          key: 'petitioner_citizenship',
          label: 'Ciudadanía del peticionario',
          type: 'select',
          options: ['Ciudadano de EE.UU.', 'Residente permanente (Green Card)', 'Otro'],
        },
        {
          key: 'petitioner_address',
          label: 'Dirección del peticionario',
          type: 'text',
        },
        {
          key: 'petitioner_phone',
          label: 'Teléfono del peticionario',
          type: 'phone',
        },
        {
          key: 'affidavit_of_support',
          label: '¿El peticionario presentará Declaración Jurada de Manutención (I-864)?',
          type: 'boolean',
          helper: 'Generalmente requerido para peticiones familiares',
        },
        {
          key: 'joint_sponsor_needed',
          label: '¿Se necesita un co-patrocinador (joint sponsor)?',
          type: 'boolean',
        },
        {
          key: 'joint_sponsor_name',
          label: 'Nombre del co-patrocinador',
          type: 'text',
          conditional: 'joint_sponsor_needed === true',
        },
      ],
    },
    {
      step: 4,
      title: 'Preguntas de Admisibilidad',
      description: 'Preguntas sobre antecedentes que pueden afectar la admisibilidad',
      type: 'form',
      fields: [
        {
          key: 'criminal_arrest',
          label: '¿Ha sido arrestado, acusado, o condenado por un crimen?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'criminal_details',
          label: 'Detalles de arrestos o condenas',
          type: 'long_text',
          conditional: 'criminal_arrest === true',
          helper: 'Incluya cada incidente: fecha, lugar, cargo, resultado',
        },
        {
          key: 'immigration_violations',
          label: '¿Ha violado alguna ley de inmigración?',
          type: 'boolean',
          required: true,
          helper: 'Incluye permanencia indebida, trabajo sin autorización, entradas ilegales',
        },
        {
          key: 'immigration_violation_details',
          label: 'Detalles de violaciones migratorias',
          type: 'long_text',
          conditional: 'immigration_violations === true',
        },
        {
          key: 'overstayed',
          label: '¿Se quedó más tiempo del autorizado en EE.UU.?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'overstay_duration',
          label: 'Duración aproximada de la permanencia indebida',
          type: 'text',
          conditional: 'overstayed === true',
        },
        {
          key: 'unauthorized_employment',
          label: '¿Trabajó sin autorización en EE.UU.?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'unlawful_presence',
          label: '¿Ha acumulado presencia ilegal en EE.UU.?',
          type: 'boolean',
          required: true,
          helper: 'Más de 180 días de presencia ilegal puede generar barras de inadmisibilidad',
        },
        {
          key: 'unlawful_presence_details',
          label: 'Detalles de la presencia ilegal',
          type: 'long_text',
          conditional: 'unlawful_presence === true',
        },
        {
          key: 'deportation_order',
          label: '¿Ha recibido una orden de deportación o exclusión?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'deportation_details',
          label: 'Detalles de la orden de deportación',
          type: 'long_text',
          conditional: 'deportation_order === true',
        },
        {
          key: 'fraud_misrepresentation',
          label: '¿Ha obtenido beneficios migratorios mediante fraude o falsedad?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'fraud_details',
          label: 'Detalles del fraude o falsedad',
          type: 'long_text',
          conditional: 'fraud_misrepresentation === true',
        },
        {
          key: 'public_charge',
          label: '¿Ha recibido beneficios públicos (SNAP, Medicaid, TANF, etc.)?',
          type: 'boolean',
          required: true,
          helper: 'Puede afectar la admisibilidad bajo la regla de carga pública',
        },
        {
          key: 'public_charge_details',
          label: 'Detalles de beneficios públicos recibidos',
          type: 'long_text',
          conditional: 'public_charge === true',
        },
        {
          key: 'communicable_disease',
          label: '¿Tiene una enfermedad transmisible de importancia pública?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'vaccination_records',
          label: '¿Tiene las vacunas requeridas al día?',
          type: 'boolean',
          required: true,
          helper: 'Se requiere examen médico (I-693) con vacunas al día',
        },
        {
          key: 'terrorism_affiliation',
          label: '¿Ha participado en o apoyado actividades terroristas?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'other_inadmissibility',
          label: '¿Hay alguna otra razón que pueda afectar su admisibilidad?',
          type: 'boolean',
        },
        {
          key: 'other_inadmissibility_details',
          label: 'Detalles adicionales',
          type: 'long_text',
          conditional: 'other_inadmissibility === true',
        },
      ],
    },
    {
      step: 5,
      title: 'Documentos de Soporte',
      description: 'Suba los documentos requeridos para la solicitud I-485',
      type: 'documents',
    },
    {
      step: 6,
      title: 'Revisión y Firma',
      description: 'Revise toda la información antes de enviar la solicitud de ajuste de estatus',
      type: 'review',
    },
  ],
  required_documents: [
    { key: 'passport', label: 'Pasaporte vigente', required: true, category: 'identidad' },
    { key: 'birth_certificate', label: 'Acta de nacimiento', required: true, category: 'identidad' },
    {
      key: 'passport_photos',
      label: 'Fotos tipo pasaporte',
      required: true,
      category: 'identidad',
      helper: '2 fotos tamaño pasaporte recientes',
    },
    { key: 'photo_id', label: 'Identificación con foto', required: true, category: 'identidad' },
    {
      key: 'i94',
      label: 'Registro I-94',
      required: false,
      category: 'inmigración',
    },
    {
      key: 'visa_documents',
      label: 'Documentos de visa / entrada',
      required: false,
      category: 'inmigración',
      multiple: true,
    },
    {
      key: 'petition_approval',
      label: 'Notificación de aprobación de petición (I-797)',
      required: true,
      category: 'petición',
      helper: 'Aprobación de I-130, I-140, u otra petición base',
    },
    {
      key: 'medical_exam',
      label: 'Examen médico I-693',
      required: true,
      category: 'médico',
      helper: 'Debe ser realizado por un médico designado por USCIS (civil surgeon)',
    },
    {
      key: 'affidavit_of_support',
      label: 'Declaración Jurada de Manutención I-864',
      required: true,
      category: 'financiero',
      helper: 'Incluya declaraciones de impuestos y evidencia de ingresos del patrocinador',
    },
    {
      key: 'sponsor_tax_returns',
      label: 'Declaraciones de impuestos del patrocinador',
      required: true,
      category: 'financiero',
      multiple: true,
      helper: 'Últimos 3 años de tax returns del patrocinador',
    },
    {
      key: 'sponsor_employment_letter',
      label: 'Carta de empleo del patrocinador',
      required: false,
      category: 'financiero',
    },
    {
      key: 'marriage_certificate',
      label: 'Acta de matrimonio',
      required: false,
      category: 'familia',
      helper: 'Si la petición está basada en matrimonio',
    },
    {
      key: 'bona_fide_marriage_evidence',
      label: 'Evidencia de matrimonio genuino',
      required: false,
      category: 'familia',
      multiple: true,
      helper: 'Fotos juntos, cuentas conjuntas, contratos de renta, declaraciones, etc.',
    },
    {
      key: 'divorce_certificates',
      label: 'Certificados de divorcios anteriores',
      required: false,
      category: 'familia',
      multiple: true,
      helper: 'De todos los matrimonios anteriores (suyo y del cónyuge)',
    },
    {
      key: 'criminal_records',
      label: 'Registros de antecedentes penales',
      required: false,
      category: 'antecedentes',
      multiple: true,
      helper: 'Si ha sido arrestado o condenado, incluya disposiciones del caso',
    },
    {
      key: 'court_records',
      label: 'Registros judiciales',
      required: false,
      category: 'antecedentes',
      multiple: true,
    },
  ],
  eligibility_questions: [
    {
      id: 'in_us',
      question: '¿Se encuentra físicamente en EE.UU.?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'Debe estar físicamente presente en EE.UU. para solicitar ajuste de estatus.',
    },
    {
      id: 'has_basis',
      question: '¿Tiene una petición aprobada o base legal para ajustar su estatus?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'Necesita una petición aprobada o base legal válida para solicitar el ajuste de estatus.',
    },
    {
      id: 'admissible',
      question: '¿Cree que es admisible (sin antecedentes penales graves, fraude, etc.)?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'Puede haber barreras de admisibilidad. Henry evaluará si existe un perdón (waiver) disponible.',
    },
  ],
}
