import type { ServiceWorkflow, WorkflowStep } from '@/types/wizard'

export const asiloAfirmativoSteps: WorkflowStep[] = [
  {
    step: 1,
    title: 'Información Personal',
    description: 'Parte A.I del formulario I-589 — Datos personales del solicitante',
    type: 'form',
    fields: [
      { key: 'legal_last_name', label: 'Apellido legal', type: 'text', required: true },
      { key: 'legal_first_name', label: 'Nombre legal', type: 'text', required: true },
      { key: 'legal_middle_name', label: 'Segundo nombre', type: 'text' },
      {
        key: 'other_names',
        label: 'Otros nombres usados',
        type: 'text_array',
        helper: 'Incluya nombres de soltera, alias, o cualquier otro nombre usado',
      },
      { key: 'residence_address_street', label: 'Dirección de residencia (calle)', type: 'text', required: true },
      { key: 'residence_address_city', label: 'Ciudad', type: 'text', required: true },
      { key: 'residence_address_state', label: 'Estado', type: 'us_state_select', required: true },
      { key: 'residence_address_zip', label: 'Código postal', type: 'text', required: true },
      { key: 'residence_phone', label: 'Teléfono', type: 'phone', required: true },
      {
        key: 'mailing_same_as_residence',
        label: '¿La dirección postal es la misma que la de residencia?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'mailing_address',
        label: 'Dirección postal',
        type: 'address_group',
        conditional: 'mailing_same_as_residence === false',
      },
      {
        key: 'gender',
        label: 'Sexo',
        type: 'select',
        options: ['Masculino', 'Femenino'],
        required: true,
        helper: 'El formulario I-589 solo permite Masculino o Femenino',
      },
      {
        key: 'marital_status',
        label: 'Estado civil',
        type: 'select',
        options: ['Soltero/a', 'Casado/a', 'Divorciado/a', 'Viudo/a'],
        required: true,
      },
      { key: 'date_of_birth', label: 'Fecha de nacimiento', type: 'date', required: true },
      { key: 'city_of_birth', label: 'Ciudad de nacimiento', type: 'text', required: true },
      { key: 'country_of_birth', label: 'País de nacimiento', type: 'country_select', required: true },
      { key: 'nationality', label: 'Nacionalidad', type: 'country_select', required: true },
      { key: 'race_ethnicity', label: 'Raza / Etnicidad', type: 'text' },
      { key: 'religion', label: 'Religión', type: 'text' },
      { key: 'native_language', label: 'Idioma nativo', type: 'text', required: true },
      { key: 'speaks_english', label: '¿Habla inglés con fluidez?', type: 'boolean', required: true },
      { key: 'other_languages', label: 'Otros idiomas que habla', type: 'text' },
    ],
  },
  {
    step: 2,
    title: 'Información de Inmigración',
    description: 'Parte A.I (continuación) — Historial migratorio y documentos de viaje',
    type: 'form',
    fields: [
      {
        key: 'immigration_court_proceedings',
        label: '¿Está actualmente en proceso ante un tribunal de inmigración?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'last_entry_date',
        label: 'Fecha de última entrada a EE.UU.',
        type: 'date',
        required: true,
        helper: 'CRÍTICA — debe aplicar dentro de 1 año de su última entrada',
      },
      { key: 'i94_number', label: 'Número I-94', type: 'text' },
      {
        key: 'entry_status',
        label: 'Estatus de entrada',
        type: 'select',
        options: [
          'Visa de turista (B-1/B-2)',
          'Visa de estudiante (F-1)',
          'Visa de trabajo',
          'Parole',
          'Sin inspección (cruzó la frontera)',
          'TPS',
          'Otro',
        ],
        required: true,
      },
      {
        key: 'entry_status_other',
        label: 'Especifique otro estatus de entrada',
        type: 'text',
        conditional: "entry_status === 'Otro'",
      },
      {
        key: 'entry_place',
        label: 'Lugar de entrada',
        type: 'text',
        required: true,
        helper: 'Puerto de entrada, aeropuerto, o punto de cruce',
      },
      { key: 'status_expires', label: 'Fecha de expiración del estatus', type: 'date' },
      { key: 'passport_number', label: 'Número de pasaporte', type: 'text', required: true },
      { key: 'passport_country', label: 'País del pasaporte', type: 'country_select', required: true },
      { key: 'passport_expiry', label: 'Fecha de expiración del pasaporte', type: 'date', required: true },
      { key: 'travel_document_number', label: 'Número de documento de viaje', type: 'text' },
      {
        key: 'a_number',
        label: 'Número A (Alien Number)',
        type: 'text',
        helper: "Comienza con 'A' seguido de 8 o 9 dígitos",
      },
      { key: 'ssn', label: 'Número de Seguro Social (SSN)', type: 'text' },
      { key: 'uscis_account', label: 'Número de cuenta USCIS', type: 'text' },
    ],
  },
  {
    step: 3,
    title: 'Cónyuge e Hijos',
    description: 'Partes A.II y A.III — Información de familiares',
    type: 'form',
    fields: [
      { key: 'has_spouse', label: '¿Tiene cónyuge?', type: 'boolean', required: true },
      {
        key: 'spouse_info',
        label: 'Información del cónyuge',
        type: 'spouse_form',
        conditional: 'has_spouse === true',
        subfields: [
          { key: 'spouse_last_name', label: 'Apellido del cónyuge', type: 'text' },
          { key: 'spouse_first_name', label: 'Nombre del cónyuge', type: 'text' },
          { key: 'spouse_middle_name', label: 'Segundo nombre del cónyuge', type: 'text' },
          { key: 'spouse_other_names', label: 'Otros nombres del cónyuge', type: 'text' },
          { key: 'spouse_dob', label: 'Fecha de nacimiento', type: 'date' },
          {
            key: 'spouse_gender',
            label: 'Sexo del cónyuge',
            type: 'select',
            options: ['Masculino', 'Femenino'],
          },
          { key: 'spouse_nationality', label: 'Nacionalidad del cónyuge', type: 'country_select' },
          { key: 'spouse_a_number', label: 'Número A del cónyuge', type: 'text' },
          { key: 'spouse_ssn', label: 'SSN del cónyuge', type: 'text' },
          { key: 'spouse_in_us', label: '¿El cónyuge está en EE.UU.?', type: 'boolean' },
          {
            key: 'spouse_include_in_application',
            label: '¿Incluir cónyuge en la solicitud de asilo?',
            type: 'boolean',
          },
          { key: 'spouse_immigration_status', label: 'Estatus migratorio del cónyuge', type: 'text' },
          { key: 'marriage_date', label: 'Fecha de matrimonio', type: 'date' },
          { key: 'marriage_place', label: 'Lugar de matrimonio', type: 'text' },
        ],
      },
      { key: 'has_children', label: '¿Tiene hijos?', type: 'boolean', required: true },
      {
        key: 'children',
        label: 'Información de los hijos',
        type: 'repeatable_group',
        conditional: 'has_children === true',
        subfields: [
          { key: 'child_last_name', label: 'Apellido del hijo/a', type: 'text' },
          { key: 'child_first_name', label: 'Nombre del hijo/a', type: 'text' },
          { key: 'child_dob', label: 'Fecha de nacimiento', type: 'date' },
          {
            key: 'child_gender',
            label: 'Sexo',
            type: 'select',
            options: ['Masculino', 'Femenino'],
          },
          { key: 'child_country_of_birth', label: 'País de nacimiento', type: 'country_select' },
          { key: 'child_nationality', label: 'Nacionalidad', type: 'country_select' },
          { key: 'child_a_number', label: 'Número A del hijo/a', type: 'text' },
          { key: 'child_in_us', label: '¿El hijo/a está en EE.UU.?', type: 'boolean' },
          {
            key: 'child_include_in_application',
            label: '¿Incluir en la solicitud de asilo?',
            type: 'boolean',
          },
          {
            key: 'child_marital_status',
            label: '¿El hijo/a es soltero/a y menor de 21?',
            type: 'boolean',
            helper: 'Debe ser soltero/a y menor de 21 para ser incluido en la solicitud',
          },
        ],
      },
    ],
  },
  {
    step: 4,
    title: 'Historial de Residencia y Empleo',
    description: 'Parte A.IV — Direcciones, empleos y educación en los últimos 5 años',
    type: 'form',
    fields: [
      {
        key: 'residences_last_5_years',
        label: 'Residencias en los últimos 5 años',
        type: 'repeatable_group',
        helper: 'Empezando por la más reciente',
        subfields: [
          { key: 'res_address', label: 'Dirección', type: 'text' },
          { key: 'res_city', label: 'Ciudad', type: 'text' },
          { key: 'res_country', label: 'País', type: 'country_select' },
          { key: 'res_from', label: 'Desde', type: 'month_year' },
          { key: 'res_to', label: 'Hasta', type: 'month_year_or_present' },
        ],
      },
      {
        key: 'employment_last_5_years',
        label: 'Empleos en los últimos 5 años',
        type: 'repeatable_group',
        helper: 'Incluya en su país y en EE.UU.',
        subfields: [
          { key: 'emp_employer', label: 'Empleador', type: 'text' },
          { key: 'emp_address', label: 'Dirección', type: 'text' },
          { key: 'emp_occupation', label: 'Ocupación', type: 'text' },
          { key: 'emp_from', label: 'Desde', type: 'month_year' },
          { key: 'emp_to', label: 'Hasta', type: 'month_year_or_present' },
        ],
      },
      {
        key: 'education',
        label: 'Educación',
        type: 'repeatable_group',
        subfields: [
          { key: 'edu_school', label: 'Escuela o institución', type: 'text' },
          { key: 'edu_type', label: 'Tipo de estudio', type: 'text' },
          { key: 'edu_location', label: 'Ubicación', type: 'text' },
          { key: 'edu_from', label: 'Desde', type: 'month_year' },
          { key: 'edu_to', label: 'Hasta', type: 'month_year_or_present' },
        ],
      },
    ],
  },
  {
    step: 5,
    title: 'Historia de Persecución',
    description: 'Parte B — La sección más importante. Describa las razones por las que solicita asilo.',
    type: 'form',
    fields: [
      {
        key: 'persecution_grounds',
        label: 'Bases de persecución',
        type: 'multi_select',
        options: [
          'Raza',
          'Religión',
          'Nacionalidad',
          'Opinión política',
          'Pertenencia a un grupo social particular',
        ],
        required: true,
      },
      {
        key: 'past_harm',
        label: '¿Ha sufrido daño o persecución en el pasado?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'past_harm_description',
        label: 'Descripción del daño sufrido',
        type: 'long_text',
        conditional: 'past_harm === true',
        required: true,
        helper: 'Incluya: QUIÉN le hizo daño, QUÉ le hicieron, CUÁNDO ocurrió, DÓNDE ocurrió, POR QUÉ cree que le persiguieron',
        min_length: 200,
      },
      {
        key: 'fear_of_return',
        label: '¿Tiene miedo de regresar a su país?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'fear_description',
        label: 'Descripción del miedo de regresar',
        type: 'long_text',
        conditional: 'fear_of_return === true',
        required: true,
        min_length: 150,
      },
      {
        key: 'harm_perpetrators',
        label: '¿Quién le causó daño o amenazó?',
        type: 'long_text',
        required: true,
        helper: 'Identifique personas u organizaciones responsables',
      },
      {
        key: 'reported_to_authorities',
        label: '¿Reportó los hechos a las autoridades?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'authority_response',
        label: '¿Qué hicieron las autoridades?',
        type: 'long_text',
        conditional: 'reported_to_authorities === true',
      },
      {
        key: 'why_not_reported',
        label: '¿Por qué no reportó a las autoridades?',
        type: 'long_text',
        conditional: 'reported_to_authorities === false',
      },
      {
        key: 'organization_membership',
        label: 'Membresía en organizaciones',
        type: 'long_text',
        helper: 'Liste cada organización con fechas de membresía',
      },
      {
        key: 'continued_membership',
        label: '¿Continúa siendo miembro de alguna organización?',
        type: 'boolean',
      },
    ],
  },
  {
    step: 6,
    title: 'Información Adicional',
    description: 'Parte C — Preguntas adicionales sobre su caso y antecedentes',
    type: 'form',
    fields: [
      {
        key: 'prior_asylum_application',
        label: '¿Ha solicitado asilo anteriormente en EE.UU.?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'prior_asylum_details',
        label: 'Detalles de la solicitud anterior',
        type: 'long_text',
        conditional: 'prior_asylum_application === true',
      },
      {
        key: 'arrested_detained',
        label: '¿Ha sido arrestado, detenido o encarcelado?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'arrested_details',
        label: 'Detalles del arresto o detención',
        type: 'long_text',
        conditional: 'arrested_detained === true',
      },
      {
        key: 'caused_harm',
        label: '¿Ha causado daño a otra persona?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'caused_harm_details',
        label: 'Detalles del daño causado',
        type: 'long_text',
        conditional: 'caused_harm === true',
      },
      {
        key: 'return_other_country',
        label: '¿Podría regresar a otro país además de su país de origen?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'return_other_country_explanation',
        label: 'Explique la posibilidad de regresar a otro país',
        type: 'long_text',
      },
      {
        key: 'convention_against_torture',
        label: '¿Solicita protección bajo la Convención Contra la Tortura (CAT)?',
        type: 'boolean',
        required: true,
        helper: 'Protección adicional si teme ser torturado. Henry le explicará los detalles.',
      },
      {
        key: 'us_government_affiliation',
        label: '¿Ha tenido alguna afiliación con el gobierno de EE.UU.?',
        type: 'boolean',
        required: true,
      },
      {
        key: 'us_government_details',
        label: 'Detalles de la afiliación gubernamental',
        type: 'long_text',
        conditional: 'us_government_affiliation === true',
      },
    ],
  },
  {
    step: 7,
    title: 'Historial de Viajes',
    description: 'Información sobre su viaje a EE.UU. y otros países visitados',
    type: 'form',
    fields: [
      {
        key: 'travel_to_us',
        label: 'Describa su viaje a EE.UU.',
        type: 'long_text',
        required: true,
        helper: '¿Desde qué país salió? ¿Por qué países pasó? ¿Cómo viajó?',
      },
      {
        key: 'countries_visited',
        label: 'Países visitados antes de llegar a EE.UU.',
        type: 'repeatable_group',
        subfields: [
          { key: 'country', label: 'País', type: 'country_select' },
          { key: 'duration', label: 'Duración de la estancia', type: 'text' },
          { key: 'purpose', label: 'Propósito de la visita', type: 'text' },
        ],
      },
      {
        key: 'applied_asylum_other_country',
        label: '¿Solicitó asilo en otro país?',
        type: 'boolean',
      },
      {
        key: 'other_country_asylum_details',
        label: 'Detalles de solicitud de asilo en otro país',
        type: 'long_text',
        conditional: 'applied_asylum_other_country === true',
      },
    ],
  },
  {
    step: 8,
    title: 'Documentos de Soporte',
    description: 'Suba los documentos necesarios para respaldar su solicitud de asilo',
    type: 'documents',
  },
  {
    step: 9,
    title: 'Revisión y Firma',
    description: 'Revise toda la información proporcionada antes de enviar su solicitud',
    type: 'review',
  },
]

export const asiloAfirmativoWorkflow: ServiceWorkflow = {
  slug: 'asilo-afirmativo',
  name: 'Asilo Afirmativo',
  steps: asiloAfirmativoSteps,
  required_documents: [
    { key: 'passport', label: 'Pasaporte', required: true, category: 'identidad' },
    { key: 'photo_id', label: 'Identificación con foto', required: true, category: 'identidad' },
    {
      key: 'passport_photos',
      label: 'Fotos tipo pasaporte',
      required: true,
      category: 'identidad',
      helper: '2 fotos tamaño pasaporte recientes',
    },
    {
      key: 'birth_certificate',
      label: 'Acta de nacimiento',
      required: true,
      category: 'identidad',
    },
    { key: 'i94', label: 'Registro I-94', required: false, category: 'inmigración' },
    {
      key: 'entry_documents',
      label: 'Documentos de entrada a EE.UU.',
      required: false,
      category: 'inmigración',
    },
    {
      key: 'personal_declaration',
      label: 'Declaración personal',
      required: true,
      category: 'caso',
      helper:
        'Su historia detallada de persecución. Henry le ayudará a redactarla.',
    },
    {
      key: 'evidence_persecution',
      label: 'Evidencia de persecución',
      required: false,
      category: 'caso',
      multiple: true,
      helper: 'Fotos, reportes policiales, amenazas, artículos de prensa, etc.',
    },
    {
      key: 'country_conditions',
      label: 'Condiciones del país de origen',
      required: false,
      category: 'caso',
      multiple: true,
      helper: 'Reportes de derechos humanos, noticias, informes de organizaciones',
    },
    {
      key: 'support_letters',
      label: 'Cartas de apoyo',
      required: false,
      category: 'caso',
      multiple: true,
      helper: 'De familiares, amigos, organizaciones, o expertos',
    },
    {
      key: 'medical_records',
      label: 'Registros médicos',
      required: false,
      category: 'caso',
      helper: 'Si tiene lesiones o trauma relacionados con la persecución',
    },
    {
      key: 'marriage_certificate',
      label: 'Acta de matrimonio',
      required: false,
      category: 'familia',
    },
    {
      key: 'children_birth_certificates',
      label: 'Actas de nacimiento de hijos',
      required: false,
      category: 'familia',
      multiple: true,
    },
  ],
  eligibility_questions: [
    {
      id: 'in_us',
      question: '¿Se encuentra actualmente en Estados Unidos?',
      type: 'boolean',
      required_answer: true,
      fail_message:
        'Debe encontrarse físicamente en EE.UU. para solicitar asilo afirmativo.',
    },
    {
      id: 'arrival_within_year',
      question: '¿Llegó a EE.UU. hace menos de 1 año?',
      type: 'boolean',
      required_answer: true,
      fail_message:
        'Generalmente debe solicitar asilo dentro de 1 año de su llegada. Existen excepciones — Henry puede evaluar su caso.',
    },
    {
      id: 'in_removal',
      question: '¿Está actualmente en proceso de deportación (removal proceedings)?',
      type: 'boolean',
      required_answer: false,
      fail_message:
        'Si está en proceso de deportación, necesita asilo defensivo, no afirmativo.',
    },
    {
      id: 'persecution_basis',
      question: '¿Cuál es la base de su temor de persecución?',
      type: 'multi_select',
      options: [
        'Raza',
        'Religión',
        'Nacionalidad',
        'Opinión política',
        'Pertenencia a un grupo social particular',
      ],
      min_selections: 1,
      fail_message:
        'El asilo requiere al menos una base protegida de persecución.',
    },
  ],
}
