import type { ServiceWorkflow } from '@/types/wizard'

export const cambioDeCorteWorkflow: ServiceWorkflow = {
  slug: 'cambio-de-corte',
  name: 'Cambio de Corte (Change of Venue)',
  steps: [
    {
      step: 1,
      title: 'Información del Caso',
      description: 'Datos del caso actual en el tribunal de inmigración',
      type: 'form',
      fields: [
        { key: 'respondent_last_name', label: 'Apellido del respondente', type: 'text', required: true },
        { key: 'respondent_first_name', label: 'Nombre del respondente', type: 'text', required: true },
        { key: 'respondent_middle_name', label: 'Segundo nombre', type: 'text' },
        { key: 'a_number', label: 'Número A (Alien Number)', type: 'text', required: true },
        {
          key: 'case_number_eoir',
          label: 'Número de caso EOIR',
          type: 'text',
          helper: 'Se encuentra en las notificaciones del tribunal',
        },
        {
          key: 'current_court',
          label: 'Tribunal actual asignado',
          type: 'text',
          required: true,
          helper: 'Nombre y ciudad del tribunal de inmigración actual',
        },
        { key: 'current_judge', label: 'Juez asignado (si lo sabe)', type: 'text' },
        {
          key: 'next_hearing_date',
          label: 'Fecha de la próxima audiencia',
          type: 'date',
          required: true,
        },
        {
          key: 'hearing_type',
          label: 'Tipo de audiencia',
          type: 'select',
          options: ['Master hearing', 'Individual hearing', 'Bond hearing', 'No sé'],
          required: true,
        },
        {
          key: 'case_type',
          label: 'Tipo de caso',
          type: 'select',
          options: ['Asilo', 'Cancelación de deportación', 'Ajuste de estatus', 'Otro'],
          required: true,
        },
        {
          key: 'case_type_other',
          label: 'Especifique el tipo de caso',
          type: 'text',
          conditional: "case_type === 'Otro'",
        },
        {
          key: 'has_attorney',
          label: '¿Tiene abogado actualmente?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'attorney_name',
          label: 'Nombre del abogado',
          type: 'text',
          conditional: 'has_attorney === true',
        },
        {
          key: 'attorney_phone',
          label: 'Teléfono del abogado',
          type: 'phone',
          conditional: 'has_attorney === true',
        },
        {
          key: 'respondent_current_address',
          label: 'Dirección actual de residencia',
          type: 'text',
          required: true,
        },
        { key: 'respondent_current_city', label: 'Ciudad actual', type: 'text', required: true },
        { key: 'respondent_current_state', label: 'Estado actual', type: 'us_state_select', required: true },
        { key: 'respondent_current_zip', label: 'Código postal', type: 'text', required: true },
        { key: 'respondent_phone', label: 'Teléfono', type: 'phone', required: true },
      ],
    },
    {
      step: 2,
      title: 'Nueva Ubicación Solicitada',
      description: 'Información sobre el tribunal al que desea transferir su caso',
      type: 'form',
      fields: [
        {
          key: 'requested_court',
          label: 'Tribunal de inmigración solicitado',
          type: 'text',
          required: true,
          helper: 'Nombre y ciudad del tribunal al que desea transferir el caso',
        },
        { key: 'new_address_street', label: 'Nueva dirección (calle)', type: 'text', required: true },
        { key: 'new_address_city', label: 'Ciudad nueva', type: 'text', required: true },
        { key: 'new_address_state', label: 'Estado nuevo', type: 'us_state_select', required: true },
        { key: 'new_address_zip', label: 'Código postal', type: 'text', required: true },
        {
          key: 'already_moved',
          label: '¿Ya se mudó a la nueva dirección?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'move_date',
          label: 'Fecha en que se mudó o planea mudarse',
          type: 'date',
        },
        {
          key: 'distance_to_current_court',
          label: 'Distancia aproximada al tribunal actual',
          type: 'text',
          helper: 'En millas o tiempo de viaje',
        },
        {
          key: 'distance_to_new_court',
          label: 'Distancia aproximada al tribunal nuevo',
          type: 'text',
          helper: 'En millas o tiempo de viaje',
        },
        {
          key: 'family_at_new_location',
          label: '¿Tiene familia en la nueva ubicación?',
          type: 'boolean',
        },
        {
          key: 'family_details',
          label: 'Detalles de familia en la nueva ubicación',
          type: 'long_text',
          conditional: 'family_at_new_location === true',
        },
        {
          key: 'employment_at_new_location',
          label: '¿Tiene empleo o perspectiva de empleo en la nueva ubicación?',
          type: 'boolean',
        },
        {
          key: 'new_attorney',
          label: '¿Tendrá abogado en la nueva ubicación?',
          type: 'boolean',
        },
        {
          key: 'new_attorney_name',
          label: 'Nombre del nuevo abogado',
          type: 'text',
          conditional: 'new_attorney === true',
        },
      ],
    },
    {
      step: 3,
      title: 'Razones del Cambio',
      description: 'Explique por qué necesita cambiar de tribunal',
      type: 'form',
      fields: [
        {
          key: 'reason_category',
          label: 'Razón principal del cambio',
          type: 'select',
          options: [
            'Cambio de residencia',
            'Reunificación familiar',
            'Empleo',
            'Acceso a representación legal',
            'Razones médicas',
            'Seguridad personal',
            'Otra razón',
          ],
          required: true,
        },
        {
          key: 'reason_other',
          label: 'Especifique otra razón',
          type: 'text',
          conditional: "reason_category === 'Otra razón'",
        },
        {
          key: 'detailed_reason',
          label: 'Explicación detallada de la razón del cambio',
          type: 'long_text',
          required: true,
          min_length: 100,
          helper: 'Explique con detalle por qué es necesario el cambio y cómo le beneficia',
        },
        {
          key: 'hardship_if_denied',
          label: '¿Qué dificultades enfrentaría si no se aprueba el cambio?',
          type: 'long_text',
          required: true,
          min_length: 50,
        },
        {
          key: 'government_opposition',
          label: '¿Cree que el gobierno se opondrá al cambio?',
          type: 'boolean',
        },
        {
          key: 'opposition_details',
          label: 'Explique por qué podría haber oposición',
          type: 'long_text',
          conditional: 'government_opposition === true',
        },
        {
          key: 'prior_change_requests',
          label: '¿Ha solicitado un cambio de corte anteriormente?',
          type: 'boolean',
        },
        {
          key: 'prior_change_details',
          label: 'Detalles de solicitudes previas',
          type: 'long_text',
          conditional: 'prior_change_requests === true',
        },
      ],
    },
    {
      step: 4,
      title: 'Documentos de Soporte',
      description: 'Suba los documentos necesarios para la moción de cambio de corte',
      type: 'documents',
    },
    {
      step: 5,
      title: 'Revisión y Firma',
      description: 'Revise toda la información antes de enviar la moción',
      type: 'review',
    },
  ],
  required_documents: [
    {
      key: 'proof_new_address',
      label: 'Comprobante de nueva dirección',
      required: true,
      category: 'residencia',
      helper: 'Contrato de renta, factura de servicios, carta de quien lo aloja',
    },
    {
      key: 'court_notices',
      label: 'Notificaciones del tribunal actual',
      required: true,
      category: 'corte',
      multiple: true,
    },
    {
      key: 'photo_id',
      label: 'Identificación con foto',
      required: true,
      category: 'identidad',
    },
    {
      key: 'proof_of_hardship',
      label: 'Evidencia de dificultad',
      required: false,
      category: 'caso',
      multiple: true,
      helper: 'Documentos que demuestren las dificultades de asistir al tribunal actual',
    },
    {
      key: 'family_evidence',
      label: 'Evidencia de lazos familiares en nueva ubicación',
      required: false,
      category: 'caso',
      multiple: true,
    },
    {
      key: 'employment_letter',
      label: 'Carta de empleo en nueva ubicación',
      required: false,
      category: 'caso',
    },
    {
      key: 'attorney_entry_of_appearance',
      label: 'EOIR-28 del abogado (si tiene representación)',
      required: false,
      category: 'legal',
    },
  ],
  eligibility_questions: [
    {
      id: 'in_removal',
      question: '¿Tiene un caso abierto en un tribunal de inmigración?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'El cambio de corte solo aplica si tiene un caso abierto en un tribunal de inmigración.',
    },
    {
      id: 'reason_exists',
      question: '¿Tiene una razón válida para solicitar el cambio (mudanza, familia, empleo, etc.)?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'Necesita una razón justificada para solicitar el cambio de corte.',
    },
  ],
}
