import type { ServiceWorkflow } from '@/types/wizard'

export const itinNumberWorkflow: ServiceWorkflow = {
  slug: 'itin-number',
  name: 'Número ITIN (W-7)',
  steps: [
    {
      step: 1,
      title: 'Información del Solicitante',
      description: 'Datos personales para el formulario W-7 (Solicitud de ITIN)',
      type: 'form',
      fields: [
        { key: 'applicant_last_name', label: 'Apellido', type: 'text', required: true },
        { key: 'applicant_first_name', label: 'Nombre', type: 'text', required: true },
        { key: 'applicant_middle_name', label: 'Segundo nombre', type: 'text' },
        {
          key: 'applicant_birth_name',
          label: 'Nombre de nacimiento (si es diferente)',
          type: 'text',
          helper: 'Solo si su nombre legal actual es diferente al de nacimiento',
        },
        { key: 'applicant_dob', label: 'Fecha de nacimiento', type: 'date', required: true },
        {
          key: 'applicant_gender',
          label: 'Sexo',
          type: 'select',
          options: ['Masculino', 'Femenino'],
          required: true,
        },
        { key: 'applicant_country_of_birth', label: 'País de nacimiento', type: 'country_select', required: true },
        { key: 'applicant_citizenship', label: 'País de ciudadanía', type: 'country_select', required: true },
        { key: 'applicant_address_street', label: 'Dirección en EE.UU. (calle)', type: 'text', required: true },
        { key: 'applicant_address_city', label: 'Ciudad', type: 'text', required: true },
        { key: 'applicant_address_state', label: 'Estado', type: 'us_state_select', required: true },
        { key: 'applicant_address_zip', label: 'Código postal', type: 'text', required: true },
        {
          key: 'has_foreign_address',
          label: '¿Tiene dirección en el extranjero?',
          type: 'boolean',
        },
        {
          key: 'foreign_address',
          label: 'Dirección en el extranjero',
          type: 'address_group',
          conditional: 'has_foreign_address === true',
        },
        { key: 'applicant_phone', label: 'Teléfono', type: 'phone', required: true },
        { key: 'applicant_email', label: 'Correo electrónico', type: 'email' },
        {
          key: 'reason_for_itin',
          label: 'Razón para solicitar el ITIN',
          type: 'select',
          options: [
            'Residente no ciudadano que presenta declaración de impuestos',
            'Ciudadano de EE.UU. / residente que presenta declaración y reclama excepción',
            'Dependiente de ciudadano/residente de EE.UU.',
            'Cónyuge de ciudadano/residente de EE.UU.',
            'Estudiante, profesor o investigador no residente que presenta declaración',
            'Dependiente o cónyuge de titular de visa no residente',
            'Otra razón',
          ],
          required: true,
        },
        {
          key: 'reason_other',
          label: 'Especifique otra razón',
          type: 'text',
          conditional: "reason_for_itin === 'Otra razón'",
        },
        {
          key: 'has_ssn',
          label: '¿Tiene o ha tenido un SSN?',
          type: 'boolean',
          required: true,
          helper: 'Si es elegible para un SSN, no puede solicitar un ITIN',
        },
        {
          key: 'previous_itin',
          label: '¿Ha tenido un ITIN anteriormente?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'previous_itin_number',
          label: 'Número de ITIN anterior',
          type: 'text',
          conditional: 'previous_itin === true',
        },
        {
          key: 'previous_itin_name',
          label: 'Nombre usado en el ITIN anterior',
          type: 'text',
          conditional: 'previous_itin === true',
        },
        {
          key: 'visa_type',
          label: 'Tipo de visa (si tiene)',
          type: 'text',
          helper: 'Ingrese el tipo de visa si entró con una',
        },
        {
          key: 'visa_number',
          label: 'Número de visa',
          type: 'text',
        },
        {
          key: 'entry_date',
          label: 'Fecha de entrada a EE.UU.',
          type: 'date',
        },
        {
          key: 'passport_number',
          label: 'Número de pasaporte',
          type: 'text',
          required: true,
        },
        {
          key: 'passport_country',
          label: 'País del pasaporte',
          type: 'country_select',
          required: true,
        },
        {
          key: 'passport_expiry',
          label: 'Fecha de expiración del pasaporte',
          type: 'date',
          required: true,
        },
      ],
    },
    {
      step: 2,
      title: 'Información de Declaración de Impuestos',
      description: 'Detalles sobre la declaración de impuestos que acompañará la solicitud W-7',
      type: 'form',
      fields: [
        {
          key: 'filing_tax_return',
          label: '¿Presentará una declaración de impuestos con esta solicitud?',
          type: 'boolean',
          required: true,
          helper: 'Generalmente se requiere presentar una declaración con la solicitud W-7',
        },
        {
          key: 'tax_year',
          label: 'Año fiscal de la declaración',
          type: 'select',
          options: ['2025', '2024', '2023', '2022'],
          required: true,
        },
        {
          key: 'filing_status',
          label: 'Estado de declaración',
          type: 'select',
          options: [
            'Soltero (Single)',
            'Casado declarando en conjunto (Married Filing Jointly)',
            'Casado declarando por separado (Married Filing Separately)',
            'Cabeza de familia (Head of Household)',
            'Viudo/a calificado/a (Qualifying Surviving Spouse)',
          ],
        },
        {
          key: 'primary_ssn_or_itin',
          label: 'SSN o ITIN del contribuyente principal (si no es usted)',
          type: 'text',
          helper: 'Si usted es cónyuge o dependiente, ingrese el ID del contribuyente principal',
        },
        {
          key: 'primary_taxpayer_name',
          label: 'Nombre del contribuyente principal',
          type: 'text',
          helper: 'Si usted es cónyuge o dependiente',
        },
        {
          key: 'estimated_income',
          label: 'Ingreso estimado para el año fiscal',
          type: 'currency',
        },
        {
          key: 'income_sources',
          label: 'Fuentes de ingreso',
          type: 'multi_select',
          options: [
            'Empleo (W-2)',
            'Trabajo independiente',
            'Trabajo en efectivo',
            'No tuve ingresos (soy dependiente)',
            'Otro',
          ],
        },
        {
          key: 'applying_as',
          label: '¿Está aplicando el ITIN para sí mismo o para otra persona?',
          type: 'select',
          options: [
            'Para mí mismo',
            'Para mi cónyuge',
            'Para mi dependiente (hijo/a menor)',
            'Para otro dependiente',
          ],
          required: true,
        },
        {
          key: 'dependent_on_return',
          label: '¿Será reclamado como dependiente en la declaración de otra persona?',
          type: 'boolean',
        },
        {
          key: 'acceptance_agent',
          label: '¿Usará un Agente de Aceptación Certificado (CAA)?',
          type: 'boolean',
          helper: 'Un CAA puede verificar sus documentos para que no tenga que enviar originales',
        },
      ],
    },
    {
      step: 3,
      title: 'Documentos de Identificación',
      description: 'Suba los documentos requeridos para verificar su identidad y estatus migratorio',
      type: 'documents',
    },
    {
      step: 4,
      title: 'Revisión y Firma',
      description: 'Revise toda la información antes de enviar la solicitud W-7',
      type: 'review',
    },
  ],
  required_documents: [
    {
      key: 'passport',
      label: 'Pasaporte vigente',
      required: true,
      category: 'identidad',
      helper: 'Documento principal de identificación. Se recomienda usar un CAA para no enviar el original.',
    },
    {
      key: 'passport_photos',
      label: 'Fotos tipo pasaporte',
      required: true,
      category: 'identidad',
    },
    {
      key: 'birth_certificate',
      label: 'Acta de nacimiento',
      required: false,
      category: 'identidad',
      helper: 'Si no tiene pasaporte, puede usar acta de nacimiento + otro documento',
    },
    {
      key: 'consular_id',
      label: 'Matrícula consular o ID consular',
      required: false,
      category: 'identidad',
    },
    {
      key: 'national_id',
      label: 'Identificación nacional del país de origen',
      required: false,
      category: 'identidad',
    },
    {
      key: 'visa_document',
      label: 'Visa de EE.UU. (si tiene)',
      required: false,
      category: 'inmigración',
    },
    {
      key: 'i94',
      label: 'Registro I-94',
      required: false,
      category: 'inmigración',
    },
    {
      key: 'tax_return_draft',
      label: 'Declaración de impuestos a adjuntar',
      required: true,
      category: 'tributario',
      helper: 'Henry le ayudará a preparar la declaración que acompañará al W-7',
    },
    {
      key: 'w2_or_1099',
      label: 'W-2 o 1099 (si tiene)',
      required: false,
      category: 'tributario',
      multiple: true,
    },
    {
      key: 'previous_itin_letter',
      label: 'Carta de ITIN anterior (si aplica)',
      required: false,
      category: 'identidad',
    },
    {
      key: 'school_records',
      label: 'Registros escolares (para dependientes menores)',
      required: false,
      category: 'identidad',
      helper: 'Para niños menores de 6 años: registros médicos pueden sustituir',
    },
    {
      key: 'medical_records',
      label: 'Registros médicos (para dependientes menores de 6 años)',
      required: false,
      category: 'identidad',
    },
  ],
  eligibility_questions: [
    {
      id: 'no_ssn',
      question: '¿Carece de un Número de Seguro Social (SSN) y no es elegible para obtener uno?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'Si es elegible para un SSN, debe solicitarlo en lugar del ITIN.',
    },
    {
      id: 'tax_obligation',
      question: '¿Tiene obligación de presentar impuestos en EE.UU. o será reclamado como dependiente?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'El ITIN requiere una razón tributaria válida para ser emitido.',
    },
  ],
}
