import type { ServiceWorkflow } from '@/types/wizard'

export const licenciaDeConducirWorkflow: ServiceWorkflow = {
  slug: 'licencia-de-conducir',
  name: 'Licencia de Conducir',
  steps: [
    {
      step: 1,
      title: 'Información Personal',
      description: 'Datos personales para la solicitud de licencia de conducir',
      type: 'form',
      fields: [
        { key: 'legal_last_name', label: 'Apellido legal', type: 'text', required: true },
        { key: 'legal_first_name', label: 'Nombre legal', type: 'text', required: true },
        { key: 'legal_middle_name', label: 'Segundo nombre', type: 'text' },
        { key: 'date_of_birth', label: 'Fecha de nacimiento', type: 'date', required: true },
        {
          key: 'gender',
          label: 'Sexo',
          type: 'select',
          options: ['Masculino', 'Femenino', 'No binario'],
          required: true,
        },
        { key: 'current_address_street', label: 'Dirección actual (calle)', type: 'text', required: true },
        { key: 'current_address_city', label: 'Ciudad', type: 'text', required: true },
        { key: 'current_address_state', label: 'Estado', type: 'us_state_select', required: true },
        { key: 'current_address_zip', label: 'Código postal', type: 'text', required: true },
        {
          key: 'time_at_address',
          label: '¿Cuánto tiempo ha vivido en esta dirección?',
          type: 'text',
          helper: 'Ej: 6 meses, 2 años',
        },
        { key: 'phone', label: 'Teléfono', type: 'phone', required: true },
        { key: 'email', label: 'Correo electrónico', type: 'email' },
        { key: 'ssn', label: 'Número de Seguro Social (SSN)', type: 'text', helper: 'Si tiene uno' },
        { key: 'itin', label: 'ITIN', type: 'text', helper: 'Si no tiene SSN' },
        {
          key: 'country_of_birth',
          label: 'País de nacimiento',
          type: 'country_select',
          required: true,
        },
        {
          key: 'immigration_status',
          label: 'Estatus migratorio actual',
          type: 'select',
          options: [
            'Ciudadano de EE.UU.',
            'Residente permanente (Green Card)',
            'Visa de trabajo',
            'Visa de estudiante',
            'TPS',
            'DACA',
            'Asilo aprobado',
            'Solicitud de asilo pendiente',
            'Sin estatus documentado',
            'Otro',
          ],
          required: true,
          helper: 'Varios estados permiten licencias sin importar el estatus migratorio',
        },
        {
          key: 'immigration_status_other',
          label: 'Especifique otro estatus',
          type: 'text',
          conditional: "immigration_status === 'Otro'",
        },
        {
          key: 'state_applying_in',
          label: 'Estado donde solicita la licencia',
          type: 'us_state_select',
          required: true,
          helper: 'Cada estado tiene diferentes requisitos. Henry le informará los de su estado.',
        },
        {
          key: 'license_type',
          label: 'Tipo de licencia',
          type: 'select',
          options: [
            'Licencia estándar (Class C / D)',
            'REAL ID',
            'Licencia comercial (CDL)',
            'Permiso de aprendizaje (Learner\'s Permit)',
          ],
          required: true,
        },
        {
          key: 'has_previous_license',
          label: '¿Tiene o ha tenido licencia de conducir anteriormente?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'previous_license_state',
          label: 'Estado de la licencia anterior',
          type: 'us_state_select',
          conditional: 'has_previous_license === true',
        },
        {
          key: 'previous_license_country',
          label: 'País de la licencia anterior (si fue fuera de EE.UU.)',
          type: 'country_select',
          conditional: 'has_previous_license === true',
        },
        {
          key: 'previous_license_number',
          label: 'Número de la licencia anterior',
          type: 'text',
          conditional: 'has_previous_license === true',
        },
        {
          key: 'previous_license_expired',
          label: '¿La licencia anterior está vencida?',
          type: 'boolean',
          conditional: 'has_previous_license === true',
        },
        {
          key: 'license_suspended_revoked',
          label: '¿Alguna vez le suspendieron o revocaron la licencia?',
          type: 'boolean',
        },
        {
          key: 'suspension_details',
          label: 'Detalles de la suspensión o revocación',
          type: 'long_text',
          conditional: 'license_suspended_revoked === true',
        },
        {
          key: 'vision_correction',
          label: '¿Usa lentes correctivos o lentes de contacto?',
          type: 'boolean',
        },
        {
          key: 'organ_donor',
          label: '¿Desea ser donante de órganos?',
          type: 'boolean',
        },
        {
          key: 'voter_registration',
          label: '¿Desea registrarse para votar? (Solo ciudadanos)',
          type: 'boolean',
          helper: 'Solo para ciudadanos de EE.UU.',
        },
      ],
    },
    {
      step: 2,
      title: 'Documentos de Identificación',
      description: 'Suba los documentos necesarios para verificar su identidad y residencia',
      type: 'documents',
    },
    {
      step: 3,
      title: 'Revisión',
      description: 'Revise toda la información antes de proceder con la solicitud',
      type: 'review',
    },
  ],
  required_documents: [
    {
      key: 'proof_of_identity',
      label: 'Comprobante de identidad',
      required: true,
      category: 'identidad',
      helper: 'Pasaporte, acta de nacimiento, o matrícula consular',
    },
    {
      key: 'passport',
      label: 'Pasaporte',
      required: false,
      category: 'identidad',
    },
    {
      key: 'birth_certificate',
      label: 'Acta de nacimiento',
      required: false,
      category: 'identidad',
    },
    {
      key: 'consular_id',
      label: 'Matrícula consular',
      required: false,
      category: 'identidad',
    },
    {
      key: 'proof_of_residency',
      label: 'Comprobante de residencia en el estado',
      required: true,
      category: 'residencia',
      multiple: true,
      helper: 'Facturas de servicios, contrato de renta, estado de cuenta bancario. Generalmente se requieren 2 comprobantes.',
    },
    {
      key: 'proof_of_ssn_or_itin',
      label: 'Comprobante de SSN o ITIN',
      required: false,
      category: 'identidad',
      helper: 'Tarjeta de SSN, carta de ITIN, o W-2 con el número',
    },
    {
      key: 'immigration_documents',
      label: 'Documentos migratorios',
      required: false,
      category: 'inmigración',
      multiple: true,
      helper: 'Green Card, EAD, I-94, aprobación de asilo, recibo de solicitud pendiente, etc.',
    },
    {
      key: 'previous_license',
      label: 'Licencia anterior (si tiene)',
      required: false,
      category: 'licencia',
    },
    {
      key: 'foreign_license',
      label: 'Licencia extranjera (si tiene)',
      required: false,
      category: 'licencia',
      helper: 'Algunos estados la aceptan para eximir del examen práctico',
    },
    {
      key: 'proof_of_insurance',
      label: 'Comprobante de seguro de auto (si ya tiene vehículo)',
      required: false,
      category: 'vehículo',
    },
    {
      key: 'name_change_documents',
      label: 'Documentos de cambio de nombre (si aplica)',
      required: false,
      category: 'identidad',
      helper: 'Si su nombre actual es diferente al de sus documentos de identidad',
    },
  ],
  eligibility_questions: [
    {
      id: 'state_allows',
      question: '¿El estado donde vive permite obtener licencia de conducir a personas con su estatus migratorio?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'No todos los estados permiten licencias para todos los estatus migratorios. Henry verificará la elegibilidad en su estado.',
    },
    {
      id: 'minimum_age',
      question: '¿Tiene al menos 16 años de edad?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'La edad mínima para una licencia de conducir es generalmente 16 años.',
    },
  ],
}
