import type { ServiceWorkflow } from '@/types/wizard'

export const mocionesWorkflow: ServiceWorkflow = {
  slug: 'mociones',
  name: 'Mociones ante el Tribunal de Inmigración',
  steps: [
    {
      step: 1,
      title: 'Información del Caso',
      description: 'Datos del caso actual en el tribunal de inmigración',
      type: 'form',
      fields: [
        { key: 'respondent_last_name', label: 'Apellido del respondente', type: 'text', required: true },
        { key: 'respondent_first_name', label: 'Nombre del respondente', type: 'text', required: true },
        { key: 'respondent_middle_name', label: 'Segundo nombre', type: 'text' },
        {
          key: 'a_number',
          label: 'Número A (Alien Number)',
          type: 'text',
          required: true,
          helper: "Comienza con 'A' seguido de 8 o 9 dígitos",
        },
        { key: 'case_number_eoir', label: 'Número de caso EOIR', type: 'text' },
        {
          key: 'court_location',
          label: 'Tribunal de inmigración asignado',
          type: 'text',
          required: true,
        },
        { key: 'judge_name', label: 'Nombre del juez asignado (si lo sabe)', type: 'text' },
        {
          key: 'next_hearing_date',
          label: 'Fecha de la próxima audiencia (si hay)',
          type: 'date',
        },
        {
          key: 'case_status',
          label: 'Estado actual del caso',
          type: 'select',
          options: [
            'Caso abierto — pendiente de audiencia',
            'Orden de deportación emitida',
            'Orden de deportación in absentia',
            'Caso cerrado administrativamente',
            'Caso en apelación (BIA)',
            'Otro',
          ],
          required: true,
        },
        {
          key: 'case_status_other',
          label: 'Especifique el estado del caso',
          type: 'text',
          conditional: "case_status === 'Otro'",
        },
        {
          key: 'order_date',
          label: 'Fecha de la orden (si aplica)',
          type: 'date',
          helper: 'Fecha de la orden de deportación o decisión del juez',
        },
        {
          key: 'respondent_address',
          label: 'Dirección actual',
          type: 'text',
          required: true,
        },
        { key: 'respondent_city', label: 'Ciudad', type: 'text', required: true },
        { key: 'respondent_state', label: 'Estado', type: 'us_state_select', required: true },
        { key: 'respondent_zip', label: 'Código postal', type: 'text', required: true },
        { key: 'respondent_phone', label: 'Teléfono', type: 'phone', required: true },
        { key: 'respondent_email', label: 'Correo electrónico', type: 'email' },
        {
          key: 'has_attorney',
          label: '¿Tiene abogado actualmente?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'attorney_name',
          label: 'Nombre del abogado',
          type: 'text',
          conditional: 'has_attorney === true',
        },
        {
          key: 'underlying_case_type',
          label: 'Tipo de alivio que busca o buscó',
          type: 'select',
          options: ['Asilo', 'Cancelación de deportación', 'Ajuste de estatus', 'VAWA', 'Visa U', 'Otro'],
        },
      ],
    },
    {
      step: 2,
      title: 'Tipo de Moción',
      description: 'Seleccione y detalle el tipo de moción que necesita presentar',
      type: 'form',
      fields: [
        {
          key: 'motion_type',
          label: 'Tipo de moción',
          type: 'select',
          options: [
            'Moción para reabrir (Motion to Reopen)',
            'Moción para reconsiderar (Motion to Reconsider)',
            'Moción para reabrir in absentia',
            'Moción para continuar (Motion to Continue / Continuance)',
            'Moción para cambio de venue (Change of Venue)',
            'Moción para terminar procedimientos (Motion to Terminate)',
            'Moción para remand (desde BIA)',
            'Moción conjunta para reabrir',
            'Otra moción',
          ],
          required: true,
        },
        {
          key: 'motion_type_other',
          label: 'Especifique otro tipo de moción',
          type: 'text',
          conditional: "motion_type === 'Otra moción'",
        },
        {
          key: 'motion_reason',
          label: 'Razón principal de la moción',
          type: 'long_text',
          required: true,
          min_length: 100,
          helper: 'Explique detalladamente por qué solicita esta moción',
        },
        {
          key: 'new_evidence',
          label: '¿Tiene nueva evidencia que no estaba disponible antes?',
          type: 'boolean',
          helper: 'Requerido para mociones de reapertura',
        },
        {
          key: 'new_evidence_description',
          label: 'Describa la nueva evidencia',
          type: 'long_text',
          conditional: 'new_evidence === true',
          min_length: 50,
        },
        {
          key: 'legal_error',
          label: '¿Hubo un error legal en la decisión anterior?',
          type: 'boolean',
          helper: 'Requerido para mociones de reconsideración',
        },
        {
          key: 'legal_error_description',
          label: 'Describa el error legal',
          type: 'long_text',
          conditional: 'legal_error === true',
        },
        {
          key: 'in_absentia_reason',
          label: '¿Por qué no asistió a la audiencia?',
          type: 'select',
          options: [
            'No recibí la notificación',
            'La notificación fue enviada a dirección incorrecta',
            'Circunstancias excepcionales (enfermedad, emergencia)',
            'Mal consejo de abogado anterior',
            'No aplica',
          ],
          conditional: "motion_type === 'Moción para reabrir in absentia'",
        },
        {
          key: 'in_absentia_explanation',
          label: 'Explicación detallada de la ausencia',
          type: 'long_text',
          conditional: "motion_type === 'Moción para reabrir in absentia'",
          min_length: 100,
        },
        {
          key: 'time_since_order',
          label: '¿Cuánto tiempo ha pasado desde la orden o decisión?',
          type: 'text',
          helper: 'Las mociones tienen plazos estrictos. Generalmente 90 días para reabrir, 30 días para reconsiderar.',
        },
        {
          key: 'within_deadline',
          label: '¿Está dentro del plazo para presentar la moción?',
          type: 'boolean',
          required: true,
          helper: 'Si no está seguro, Henry le ayudará a determinar el plazo',
        },
        {
          key: 'deadline_exception',
          label: '¿Existe una excepción al plazo que aplique a su caso?',
          type: 'long_text',
          conditional: 'within_deadline === false',
          helper: 'Ej: cambio de condiciones del país, fraude del abogado anterior, etc.',
        },
        {
          key: 'changed_country_conditions',
          label: '¿Han cambiado las condiciones en su país de origen?',
          type: 'boolean',
          helper: 'Puede ser excepción al plazo de 90 días',
        },
        {
          key: 'country_conditions_description',
          label: 'Describa los cambios en las condiciones del país',
          type: 'long_text',
          conditional: 'changed_country_conditions === true',
        },
        {
          key: 'prior_attorney_issue',
          label: '¿Tuvo problemas con su abogado anterior?',
          type: 'boolean',
        },
        {
          key: 'prior_attorney_details',
          label: 'Detalles de los problemas con el abogado anterior',
          type: 'long_text',
          conditional: 'prior_attorney_issue === true',
          helper: 'Incompetencia, abandono, fraude del abogado anterior',
        },
        {
          key: 'relief_sought',
          label: '¿Qué alivio busca si se concede la moción?',
          type: 'long_text',
          required: true,
          helper: 'Ej: nueva audiencia de asilo, cancelación de deportación, etc.',
        },
      ],
    },
    {
      step: 3,
      title: 'Documentos de Soporte',
      description: 'Suba los documentos necesarios para respaldar su moción',
      type: 'documents',
    },
    {
      step: 4,
      title: 'Revisión y Firma',
      description: 'Revise toda la información antes de presentar la moción al tribunal',
      type: 'review',
    },
  ],
  required_documents: [
    {
      key: 'photo_id',
      label: 'Identificación con foto',
      required: true,
      category: 'identidad',
    },
    {
      key: 'court_order',
      label: 'Orden del tribunal o decisión del juez',
      required: true,
      category: 'corte',
      helper: 'La orden de deportación o decisión que desea impugnar',
    },
    {
      key: 'court_notices',
      label: 'Notificaciones del tribunal',
      required: true,
      category: 'corte',
      multiple: true,
      helper: 'Todas las notificaciones recibidas del tribunal',
    },
    {
      key: 'nta_copy',
      label: 'Copia del Notice to Appear (NTA)',
      required: true,
      category: 'corte',
    },
    {
      key: 'new_evidence',
      label: 'Nueva evidencia',
      required: false,
      category: 'caso',
      multiple: true,
      helper: 'Documentos nuevos que respaldan su moción',
    },
    {
      key: 'personal_declaration',
      label: 'Declaración personal jurada',
      required: true,
      category: 'caso',
      helper: 'Declaración explicando las razones de la moción',
    },
    {
      key: 'country_conditions',
      label: 'Evidencia de condiciones del país',
      required: false,
      category: 'caso',
      multiple: true,
      helper: 'Si aplica: reportes actualizados sobre condiciones del país',
    },
    {
      key: 'proof_of_address',
      label: 'Comprobante de dirección',
      required: false,
      category: 'residencia',
      helper: 'Para demostrar que las notificaciones fueron enviadas a dirección incorrecta',
    },
    {
      key: 'medical_evidence',
      label: 'Evidencia médica',
      required: false,
      category: 'caso',
      helper: 'Si la moción está basada en circunstancias médicas',
    },
    {
      key: 'prior_attorney_communications',
      label: 'Comunicaciones con abogado anterior',
      required: false,
      category: 'caso',
      multiple: true,
      helper: 'Si alega ineficacia o fraude del abogado anterior',
    },
    {
      key: 'bar_complaint',
      label: 'Queja ante el bar association',
      required: false,
      category: 'caso',
      helper: 'Si presentó queja contra el abogado anterior',
    },
  ],
  eligibility_questions: [
    {
      id: 'has_case',
      question: '¿Tiene o tuvo un caso en un tribunal de inmigración?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'Las mociones se presentan ante tribunales de inmigración donde existe un caso.',
    },
    {
      id: 'knows_motion_type',
      question: '¿Sabe qué tipo de moción necesita?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'No se preocupe — Henry le ayudará a determinar el tipo de moción apropiado para su situación.',
    },
  ],
}
