import type { ServiceWorkflow } from '@/types/wizard'

export const taxesWorkflow: ServiceWorkflow = {
  slug: 'taxes',
  name: 'Declaración de Impuestos (Tax Return)',
  steps: [
    {
      step: 1,
      title: 'Información del Contribuyente',
      description: 'Datos personales del contribuyente principal',
      type: 'form',
      fields: [
        { key: 'taxpayer_last_name', label: 'Apellido', type: 'text', required: true },
        { key: 'taxpayer_first_name', label: 'Nombre', type: 'text', required: true },
        { key: 'taxpayer_middle_initial', label: 'Inicial del segundo nombre', type: 'text' },
        { key: 'taxpayer_dob', label: 'Fecha de nacimiento', type: 'date', required: true },
        {
          key: 'taxpayer_ssn_or_itin',
          label: 'SSN o ITIN',
          type: 'text',
          required: true,
          helper: 'Si no tiene SSN o ITIN, primero debe solicitar un ITIN',
        },
        {
          key: 'taxpayer_id_type',
          label: 'Tipo de identificación tributaria',
          type: 'select',
          options: ['SSN', 'ITIN'],
          required: true,
        },
        { key: 'taxpayer_address_street', label: 'Dirección (calle)', type: 'text', required: true },
        { key: 'taxpayer_address_city', label: 'Ciudad', type: 'text', required: true },
        { key: 'taxpayer_address_state', label: 'Estado', type: 'us_state_select', required: true },
        { key: 'taxpayer_address_zip', label: 'Código postal', type: 'text', required: true },
        { key: 'taxpayer_phone', label: 'Teléfono', type: 'phone', required: true },
        { key: 'taxpayer_email', label: 'Correo electrónico', type: 'email' },
        {
          key: 'filing_status',
          label: 'Estado de declaración',
          type: 'select',
          options: [
            'Soltero (Single)',
            'Casado declarando en conjunto (Married Filing Jointly)',
            'Casado declarando por separado (Married Filing Separately)',
            'Cabeza de familia (Head of Household)',
            'Viudo/a calificado/a (Qualifying Surviving Spouse)',
          ],
          required: true,
        },
        {
          key: 'tax_year',
          label: 'Año fiscal',
          type: 'select',
          options: ['2025', '2024', '2023', '2022', '2021'],
          required: true,
        },
        {
          key: 'has_spouse_filing',
          label: '¿Declara en conjunto con cónyuge?',
          type: 'boolean',
        },
        {
          key: 'spouse_last_name',
          label: 'Apellido del cónyuge',
          type: 'text',
          conditional: 'has_spouse_filing === true',
        },
        {
          key: 'spouse_first_name',
          label: 'Nombre del cónyuge',
          type: 'text',
          conditional: 'has_spouse_filing === true',
        },
        {
          key: 'spouse_ssn_or_itin',
          label: 'SSN o ITIN del cónyuge',
          type: 'text',
          conditional: 'has_spouse_filing === true',
        },
        {
          key: 'spouse_dob',
          label: 'Fecha de nacimiento del cónyuge',
          type: 'date',
          conditional: 'has_spouse_filing === true',
        },
        {
          key: 'first_time_filing',
          label: '¿Es la primera vez que declara impuestos en EE.UU.?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'bank_account',
          label: '¿Tiene cuenta bancaria en EE.UU.?',
          type: 'boolean',
          helper: 'Para recibir reembolso por depósito directo',
        },
        {
          key: 'routing_number',
          label: 'Número de ruta bancaria',
          type: 'text',
          conditional: 'bank_account === true',
        },
        {
          key: 'account_number',
          label: 'Número de cuenta',
          type: 'text',
          conditional: 'bank_account === true',
        },
        {
          key: 'account_type',
          label: 'Tipo de cuenta',
          type: 'select',
          options: ['Checking (Corriente)', 'Savings (Ahorro)'],
          conditional: 'bank_account === true',
        },
      ],
    },
    {
      step: 2,
      title: 'Dependientes',
      description: 'Información de personas que dependen económicamente de usted',
      type: 'form',
      fields: [
        { key: 'has_dependents', label: '¿Tiene dependientes?', type: 'boolean', required: true },
        {
          key: 'dependents',
          label: 'Lista de dependientes',
          type: 'repeatable_group',
          conditional: 'has_dependents === true',
          subfields: [
            { key: 'dep_first_name', label: 'Nombre del dependiente', type: 'text' },
            { key: 'dep_last_name', label: 'Apellido del dependiente', type: 'text' },
            { key: 'dep_dob', label: 'Fecha de nacimiento', type: 'date' },
            { key: 'dep_ssn_or_itin', label: 'SSN o ITIN del dependiente', type: 'text' },
            {
              key: 'dep_relationship',
              label: 'Relación',
              type: 'select',
              options: ['Hijo/a', 'Hijastro/a', 'Hijo/a adoptivo/a', 'Hermano/a', 'Padre/Madre', 'Otro familiar', 'No familiar'],
            },
            {
              key: 'dep_months_lived',
              label: 'Meses que vivió con usted durante el año',
              type: 'number',
              helper: 'Número de meses (1-12)',
            },
            {
              key: 'dep_income',
              label: '¿El dependiente tuvo ingresos propios?',
              type: 'boolean',
            },
            {
              key: 'dep_income_amount',
              label: 'Monto de ingresos del dependiente',
              type: 'currency',
              conditional: 'dep_income === true',
            },
            {
              key: 'dep_is_student',
              label: '¿Es estudiante de tiempo completo?',
              type: 'boolean',
            },
            {
              key: 'dep_disabled',
              label: '¿Tiene alguna discapacidad permanente?',
              type: 'boolean',
            },
          ],
        },
        {
          key: 'childcare_expenses',
          label: '¿Pagó gastos de cuidado de niños para poder trabajar?',
          type: 'boolean',
        },
        {
          key: 'childcare_amount',
          label: 'Monto total de gastos de cuidado de niños',
          type: 'currency',
          conditional: 'childcare_expenses === true',
        },
        {
          key: 'childcare_provider',
          label: 'Nombre del proveedor de cuidado infantil',
          type: 'text',
          conditional: 'childcare_expenses === true',
        },
        {
          key: 'childcare_provider_ein',
          label: 'EIN o SSN del proveedor',
          type: 'text',
          conditional: 'childcare_expenses === true',
        },
      ],
    },
    {
      step: 3,
      title: 'Ingresos',
      description: 'Detalle de todos los ingresos recibidos durante el año fiscal',
      type: 'form',
      fields: [
        {
          key: 'income_types',
          label: 'Tipos de ingresos recibidos',
          type: 'multi_select',
          options: [
            'Empleo (W-2)',
            'Trabajo independiente (1099-NEC/MISC)',
            'Desempleo (1099-G)',
            'Intereses bancarios (1099-INT)',
            'Dividendos (1099-DIV)',
            'Ingreso de alquiler',
            'Beneficios de Seguro Social',
            'Pensión / Retiro (1099-R)',
            'Trabajo en efectivo',
            'Otro ingreso',
          ],
          required: true,
        },
        {
          key: 'w2_employers',
          label: 'Empleadores (W-2)',
          type: 'repeatable_group',
          helper: 'Agregue cada formulario W-2 recibido',
          subfields: [
            { key: 'w2_employer_name', label: 'Nombre del empleador', type: 'text' },
            { key: 'w2_employer_ein', label: 'EIN del empleador', type: 'text' },
            { key: 'w2_wages', label: 'Salarios (Box 1)', type: 'currency' },
            { key: 'w2_federal_tax', label: 'Impuesto federal retenido (Box 2)', type: 'currency' },
            { key: 'w2_state_tax', label: 'Impuesto estatal retenido (Box 17)', type: 'currency' },
            { key: 'w2_social_security', label: 'Seguro Social retenido (Box 4)', type: 'currency' },
            { key: 'w2_medicare', label: 'Medicare retenido (Box 6)', type: 'currency' },
          ],
        },
        {
          key: 'self_employment_income',
          label: 'Ingreso por trabajo independiente',
          type: 'currency',
          helper: 'Total de formularios 1099-NEC/MISC y pagos en efectivo',
        },
        {
          key: 'self_employment_expenses',
          label: 'Gastos de trabajo independiente',
          type: 'currency',
          helper: 'Gastos deducibles relacionados con el trabajo independiente',
        },
        {
          key: 'self_employment_type',
          label: 'Tipo de trabajo independiente',
          type: 'text',
          helper: 'Descripción del tipo de trabajo (ej: limpieza, construcción, comida)',
        },
        {
          key: 'cash_income',
          label: 'Ingreso en efectivo no reportado en formularios',
          type: 'currency',
          helper: 'Todos los ingresos deben ser reportados, incluso en efectivo',
        },
        {
          key: 'unemployment_income',
          label: 'Beneficios de desempleo recibidos',
          type: 'currency',
        },
        {
          key: 'other_income',
          label: 'Otros ingresos',
          type: 'currency',
        },
        {
          key: 'other_income_description',
          label: 'Descripción de otros ingresos',
          type: 'text',
        },
        {
          key: 'foreign_income',
          label: '¿Recibió ingresos de fuera de EE.UU.?',
          type: 'boolean',
        },
        {
          key: 'foreign_income_amount',
          label: 'Monto de ingresos extranjeros',
          type: 'currency',
          conditional: 'foreign_income === true',
        },
        {
          key: 'foreign_income_country',
          label: 'País de origen del ingreso',
          type: 'country_select',
          conditional: 'foreign_income === true',
        },
      ],
    },
    {
      step: 4,
      title: 'Deducciones y Créditos',
      description: 'Gastos que pueden reducir su carga tributaria',
      type: 'form',
      fields: [
        {
          key: 'deduction_type',
          label: 'Tipo de deducción',
          type: 'select',
          options: ['Deducción estándar (Standard Deduction)', 'Deducciones detalladas (Itemized)'],
          required: true,
          helper: 'La mayoría de contribuyentes se benefician de la deducción estándar',
        },
        {
          key: 'medical_expenses',
          label: 'Gastos médicos no reembolsados',
          type: 'currency',
          conditional: "deduction_type === 'Deducciones detalladas (Itemized)'",
        },
        {
          key: 'state_local_taxes_paid',
          label: 'Impuestos estatales y locales pagados',
          type: 'currency',
          conditional: "deduction_type === 'Deducciones detalladas (Itemized)'",
          helper: 'Límite de $10,000',
        },
        {
          key: 'mortgage_interest',
          label: 'Intereses de hipoteca pagados',
          type: 'currency',
          conditional: "deduction_type === 'Deducciones detalladas (Itemized)'",
        },
        {
          key: 'charitable_donations',
          label: 'Donaciones caritativas',
          type: 'currency',
          conditional: "deduction_type === 'Deducciones detalladas (Itemized)'",
        },
        {
          key: 'education_expenses',
          label: '¿Pagó gastos educativos (tuition)?',
          type: 'boolean',
        },
        {
          key: 'education_amount',
          label: 'Monto de gastos educativos',
          type: 'currency',
          conditional: 'education_expenses === true',
        },
        {
          key: 'education_institution',
          label: 'Institución educativa',
          type: 'text',
          conditional: 'education_expenses === true',
        },
        {
          key: 'student_loan_interest',
          label: 'Intereses de préstamo estudiantil pagados',
          type: 'currency',
        },
        {
          key: 'ira_contributions',
          label: 'Contribuciones a IRA',
          type: 'currency',
        },
        {
          key: 'health_insurance',
          label: '¿Tuvo seguro de salud todo el año?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'marketplace_insurance',
          label: '¿Recibió seguro a través del Marketplace (1095-A)?',
          type: 'boolean',
        },
        {
          key: 'premium_tax_credit',
          label: 'Crédito fiscal por primas recibido',
          type: 'currency',
          conditional: 'marketplace_insurance === true',
        },
        {
          key: 'earned_income_credit',
          label: '¿Desea que se evalúe el Earned Income Tax Credit (EITC)?',
          type: 'boolean',
          helper: 'Crédito para trabajadores con ingresos bajos a moderados',
        },
        {
          key: 'child_tax_credit',
          label: '¿Desea que se evalúe el Child Tax Credit?',
          type: 'boolean',
          helper: 'Crédito por hijos menores de 17 años con SSN',
        },
        {
          key: 'estimated_taxes_paid',
          label: '¿Pagó impuestos estimados durante el año?',
          type: 'boolean',
        },
        {
          key: 'estimated_taxes_amount',
          label: 'Monto total de pagos estimados',
          type: 'currency',
          conditional: 'estimated_taxes_paid === true',
        },
      ],
    },
    {
      step: 5,
      title: 'Documentos Tributarios',
      description: 'Suba los documentos fiscales necesarios para preparar su declaración',
      type: 'documents',
    },
    {
      step: 6,
      title: 'Revisión y Firma',
      description: 'Revise toda la información antes de enviar su declaración de impuestos',
      type: 'review',
    },
  ],
  required_documents: [
    {
      key: 'photo_id',
      label: 'Identificación con foto',
      required: true,
      category: 'identidad',
    },
    {
      key: 'ssn_or_itin_card',
      label: 'Tarjeta de SSN o carta de ITIN',
      required: true,
      category: 'identidad',
    },
    {
      key: 'w2_forms',
      label: 'Formularios W-2',
      required: false,
      category: 'ingresos',
      multiple: true,
      helper: 'Un W-2 por cada empleador',
    },
    {
      key: '1099_forms',
      label: 'Formularios 1099 (todos los tipos)',
      required: false,
      category: 'ingresos',
      multiple: true,
      helper: '1099-NEC, 1099-MISC, 1099-INT, 1099-G, 1099-R, etc.',
    },
    {
      key: 'prior_tax_return',
      label: 'Declaración del año anterior (si tiene)',
      required: false,
      category: 'referencia',
    },
    {
      key: 'itin_letter',
      label: 'Carta de asignación de ITIN (si aplica)',
      required: false,
      category: 'identidad',
    },
    {
      key: 'dependent_ssn_itin',
      label: 'SSN o ITIN de dependientes',
      required: false,
      category: 'identidad',
      multiple: true,
    },
    {
      key: 'form_1095a',
      label: 'Formulario 1095-A (seguro del Marketplace)',
      required: false,
      category: 'seguros',
    },
    {
      key: 'expense_receipts',
      label: 'Recibos de gastos deducibles',
      required: false,
      category: 'deducciones',
      multiple: true,
    },
    {
      key: 'bank_statement',
      label: 'Estado de cuenta bancario (para depósito directo)',
      required: false,
      category: 'bancario',
    },
    {
      key: 'childcare_receipts',
      label: 'Recibos de cuidado de niños',
      required: false,
      category: 'deducciones',
    },
    {
      key: 'estimated_tax_payments',
      label: 'Comprobantes de pagos estimados',
      required: false,
      category: 'pagos',
      multiple: true,
    },
  ],
}
