import type { ServiceWorkflow } from '@/types/wizard'

export const visaJuvenilWorkflow: ServiceWorkflow = {
  slug: 'visa-juvenil',
  name: 'Visa Juvenil (SIJS)',
  steps: [
    {
      step: 1,
      title: 'Información del Menor',
      description: 'Datos personales del menor solicitante de Special Immigrant Juvenile Status',
      type: 'form',
      fields: [
        { key: 'minor_last_name', label: 'Apellido del menor', type: 'text', required: true },
        { key: 'minor_first_name', label: 'Nombre del menor', type: 'text', required: true },
        { key: 'minor_middle_name', label: 'Segundo nombre', type: 'text' },
        { key: 'minor_dob', label: 'Fecha de nacimiento', type: 'date', required: true },
        {
          key: 'minor_age',
          label: 'Edad actual',
          type: 'number',
          required: true,
          helper: 'Debe ser menor de 21 años al momento de solicitar',
        },
        {
          key: 'minor_gender',
          label: 'Sexo',
          type: 'select',
          options: ['Masculino', 'Femenino'],
          required: true,
        },
        { key: 'minor_country_of_birth', label: 'País de nacimiento', type: 'country_select', required: true },
        { key: 'minor_nationality', label: 'Nacionalidad', type: 'country_select', required: true },
        { key: 'minor_native_language', label: 'Idioma nativo', type: 'text', required: true },
        { key: 'minor_speaks_english', label: '¿Habla inglés?', type: 'boolean', required: true },
        { key: 'minor_current_address', label: 'Dirección actual en EE.UU.', type: 'text', required: true },
        { key: 'minor_city', label: 'Ciudad', type: 'text', required: true },
        { key: 'minor_state', label: 'Estado', type: 'us_state_select', required: true },
        { key: 'minor_zip', label: 'Código postal', type: 'text', required: true },
        { key: 'minor_phone', label: 'Teléfono de contacto', type: 'phone' },
        { key: 'minor_email', label: 'Correo electrónico', type: 'email' },
        {
          key: 'minor_entry_date',
          label: 'Fecha de entrada a EE.UU.',
          type: 'date',
          required: true,
        },
        {
          key: 'minor_entry_manner',
          label: 'Manera de entrada',
          type: 'select',
          options: ['Con visa', 'Sin inspección', 'Parole', 'Otro'],
          required: true,
        },
        { key: 'minor_a_number', label: 'Número A (si tiene)', type: 'text' },
        {
          key: 'minor_in_removal',
          label: '¿El menor está en proceso de deportación?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'minor_current_guardian',
          label: '¿Quién tiene la custodia actual del menor?',
          type: 'text',
          required: true,
          helper: 'Nombre del guardián, familiar, o agencia',
        },
        {
          key: 'minor_guardian_relationship',
          label: 'Relación con el guardián',
          type: 'select',
          options: ['Madre', 'Padre', 'Abuelo/a', 'Tío/a', 'Otro familiar', 'Familia adoptiva', 'Agencia estatal', 'Otro'],
          required: true,
        },
        {
          key: 'minor_school_enrolled',
          label: '¿Está inscrito en la escuela?',
          type: 'boolean',
        },
        { key: 'minor_school_name', label: 'Nombre de la escuela', type: 'text', conditional: 'minor_school_enrolled === true' },
        { key: 'minor_grade', label: 'Grado escolar', type: 'text', conditional: 'minor_school_enrolled === true' },
      ],
    },
    {
      step: 2,
      title: 'Información de los Padres',
      description: 'Datos sobre los padres biológicos del menor',
      type: 'form',
      fields: [
        { key: 'father_last_name', label: 'Apellido del padre', type: 'text' },
        { key: 'father_first_name', label: 'Nombre del padre', type: 'text' },
        { key: 'father_dob', label: 'Fecha de nacimiento del padre', type: 'date' },
        { key: 'father_country_of_birth', label: 'País de nacimiento del padre', type: 'country_select' },
        { key: 'father_location', label: '¿Dónde se encuentra el padre actualmente?', type: 'text' },
        {
          key: 'father_relationship_status',
          label: 'Relación actual con el padre',
          type: 'select',
          options: ['Sin contacto', 'Contacto limitado', 'Contacto regular', 'Fallecido', 'Desconocido'],
        },
        {
          key: 'father_abuse_neglect',
          label: '¿El padre abusó, abandonó, o descuidó al menor?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'father_abuse_details',
          label: 'Describa el abuso o negligencia del padre',
          type: 'long_text',
          conditional: 'father_abuse_neglect === true',
          min_length: 100,
        },
        { key: 'mother_last_name', label: 'Apellido de la madre', type: 'text' },
        { key: 'mother_first_name', label: 'Nombre de la madre', type: 'text' },
        { key: 'mother_dob', label: 'Fecha de nacimiento de la madre', type: 'date' },
        { key: 'mother_country_of_birth', label: 'País de nacimiento de la madre', type: 'country_select' },
        { key: 'mother_location', label: '¿Dónde se encuentra la madre actualmente?', type: 'text' },
        {
          key: 'mother_relationship_status',
          label: 'Relación actual con la madre',
          type: 'select',
          options: ['Sin contacto', 'Contacto limitado', 'Contacto regular', 'Fallecida', 'Desconocida'],
        },
        {
          key: 'mother_abuse_neglect',
          label: '¿La madre abusó, abandonó, o descuidó al menor?',
          type: 'boolean',
          required: true,
        },
        {
          key: 'mother_abuse_details',
          label: 'Describa el abuso o negligencia de la madre',
          type: 'long_text',
          conditional: 'mother_abuse_neglect === true',
          min_length: 100,
        },
        {
          key: 'parents_marital_status',
          label: 'Estado civil de los padres',
          type: 'select',
          options: ['Casados', 'Divorciados', 'Separados', 'Nunca casados', 'Viudo/a', 'Desconocido'],
        },
        {
          key: 'reunification_viable',
          label: '¿Es viable la reunificación con uno o ambos padres?',
          type: 'boolean',
          required: true,
          helper: 'Para SIJS, la reunificación con al menos uno de los padres no debe ser viable',
        },
        {
          key: 'reunification_explanation',
          label: '¿Por qué no es viable la reunificación?',
          type: 'long_text',
          required: true,
          min_length: 100,
        },
      ],
    },
    {
      step: 3,
      title: 'Historia de Abuso, Abandono o Negligencia',
      description: 'Detalles sobre el maltrato que fundamenta la solicitud SIJS',
      type: 'form',
      fields: [
        {
          key: 'abuse_types',
          label: 'Tipos de maltrato sufrido',
          type: 'multi_select',
          options: [
            'Abuso físico',
            'Abuso emocional/psicológico',
            'Abuso sexual',
            'Abandono',
            'Negligencia',
          ],
          required: true,
          min_selections: 1,
        },
        {
          key: 'abuse_narrative',
          label: 'Describa detalladamente el abuso, abandono o negligencia',
          type: 'long_text',
          required: true,
          min_length: 200,
          helper: 'Incluya quién, qué, cuándo, dónde. Sea lo más específico posible.',
        },
        {
          key: 'abuse_start_date',
          label: '¿Cuándo comenzó el maltrato?',
          type: 'text',
          required: true,
          helper: 'Fecha aproximada o edad del menor',
        },
        {
          key: 'abuse_ongoing',
          label: '¿El maltrato continúa o ha cesado?',
          type: 'select',
          options: ['Continúa', 'Ha cesado', 'Cesó al salir del país'],
          required: true,
        },
        {
          key: 'abuse_reported',
          label: '¿Se reportó el abuso a alguna autoridad?',
          type: 'boolean',
        },
        {
          key: 'abuse_report_details',
          label: 'Detalles del reporte',
          type: 'long_text',
          conditional: 'abuse_reported === true',
        },
        {
          key: 'therapy_received',
          label: '¿El menor ha recibido terapia o consejería?',
          type: 'boolean',
        },
        {
          key: 'therapy_details',
          label: 'Detalles de la terapia',
          type: 'long_text',
          conditional: 'therapy_received === true',
        },
        {
          key: 'state_court_involved',
          label: '¿Hay un caso en un tribunal estatal juvenil o de familia?',
          type: 'boolean',
          required: true,
          helper: 'Se requiere una orden de un tribunal estatal para SIJS',
        },
        {
          key: 'state_court_details',
          label: 'Detalles del caso en tribunal estatal',
          type: 'long_text',
          conditional: 'state_court_involved === true',
        },
        {
          key: 'state_court_state',
          label: 'Estado donde se encuentra el tribunal',
          type: 'us_state_select',
          conditional: 'state_court_involved === true',
        },
        {
          key: 'best_interest_in_us',
          label: '¿Por qué es mejor para el menor permanecer en EE.UU.?',
          type: 'long_text',
          required: true,
          min_length: 100,
          helper: 'Explique por qué regresar al país de origen no es en el mejor interés del menor',
        },
      ],
    },
    {
      step: 4,
      title: 'Documentos de Soporte',
      description: 'Suba los documentos necesarios para la solicitud SIJS',
      type: 'documents',
    },
    {
      step: 5,
      title: 'Revisión y Firma',
      description: 'Revise toda la información antes de enviar',
      type: 'review',
    },
  ],
  required_documents: [
    { key: 'minor_birth_certificate', label: 'Acta de nacimiento del menor', required: true, category: 'identidad' },
    { key: 'minor_passport', label: 'Pasaporte del menor (si tiene)', required: false, category: 'identidad' },
    { key: 'minor_photo_id', label: 'Identificación del menor', required: true, category: 'identidad' },
    { key: 'passport_photos', label: 'Fotos tipo pasaporte del menor', required: true, category: 'identidad' },
    {
      key: 'state_court_order',
      label: 'Orden del tribunal estatal (SIJ findings)',
      required: true,
      category: 'legal',
      helper: 'Orden judicial con las determinaciones de SIJS',
    },
    {
      key: 'custody_order',
      label: 'Orden de custodia',
      required: false,
      category: 'legal',
    },
    {
      key: 'guardian_id',
      label: 'Identificación del guardián',
      required: true,
      category: 'identidad',
    },
    {
      key: 'abuse_evidence',
      label: 'Evidencia del abuso o negligencia',
      required: false,
      category: 'caso',
      multiple: true,
      helper: 'Reportes policiales, médicos, fotografías, declaraciones',
    },
    {
      key: 'therapy_records',
      label: 'Registros de terapia o consejería',
      required: false,
      category: 'caso',
    },
    {
      key: 'school_records',
      label: 'Registros escolares',
      required: false,
      category: 'caso',
    },
    {
      key: 'declaration_minor',
      label: 'Declaración personal del menor',
      required: true,
      category: 'caso',
      helper: 'Henry ayudará al menor a preparar su declaración',
    },
    {
      key: 'support_letters',
      label: 'Cartas de apoyo',
      required: false,
      category: 'caso',
      multiple: true,
      helper: 'De maestros, consejeros, trabajadores sociales, familiares',
    },
  ],
  eligibility_questions: [
    {
      id: 'is_minor',
      question: '¿El solicitante es menor de 21 años?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'La visa juvenil SIJS requiere que el solicitante sea menor de 21 años.',
    },
    {
      id: 'in_us',
      question: '¿El menor se encuentra actualmente en EE.UU.?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'El menor debe estar físicamente en EE.UU. para solicitar SIJS.',
    },
    {
      id: 'unmarried',
      question: '¿El menor es soltero/a?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'El solicitante SIJS debe ser soltero/a.',
    },
    {
      id: 'abuse_abandonment',
      question: '¿El menor ha sido víctima de abuso, abandono, o negligencia por uno o ambos padres?',
      type: 'boolean',
      required_answer: true,
      fail_message: 'SIJS requiere evidencia de abuso, abandono, o negligencia parental.',
    },
  ],
}
