INSERT INTO service_catalog (name, slug, short_description, base_price, allow_installments, max_installments, min_down_payment_percent, estimated_duration, uscis_forms, required_documents, eligibility_questions, icon, display_order) VALUES
('Asilo Afirmativo', 'asilo-afirmativo', 'Solicitud de asilo ante USCIS para personas dentro de EE.UU. que no están en proceso de deportación.', 5000.00, true, 12, 20, '1-3+ años', ARRAY['I-589', 'I-765'], '[]'::jsonb, '[{"id":"in_us","question":"¿Está usted actualmente dentro de los Estados Unidos?","type":"boolean","required_answer":true,"fail_message":"Debe estar físicamente presente en EE.UU. para solicitar asilo afirmativo."},{"id":"arrival_within_year","question":"¿Llegó a Estados Unidos hace menos de 1 año?","type":"boolean","required_answer":true,"fail_message":"Generalmente debe aplicar dentro de 1 año de su llegada. Puede haber excepciones."},{"id":"in_removal","question":"¿Tiene una orden de deportación o está en proceso de remoción?","type":"boolean","required_answer":false,"fail_message":"Si está en proceso de remoción, necesita Asilo Defensivo."},{"id":"persecution_basis","question":"¿Cuál es la razón de su temor de regresar?","type":"multi_select","options":["Raza","Religión","Nacionalidad","Opinión política","Pertenencia a grupo social particular"],"min_selections":1,"fail_message":"El asilo requiere persecución basada en al menos una categoría protegida."}]'::jsonb, 'Shield', 1),

('Asilo Defensivo', 'asilo-defensivo', 'Solicitud de asilo ante Corte de Inmigración para personas en proceso de deportación.', 6000.00, true, 12, 20, '1-3+ años', ARRAY['I-589', 'EOIR-28'], '[]'::jsonb, NULL, 'Gavel', 2),

('Visa Juvenil (SIJS)', 'visa-juvenil', 'Estatus de Inmigrante Juvenil Especial para menores víctimas de abuso, negligencia o abandono.', 4000.00, true, 12, 20, '6-18 meses', ARRAY['I-360', 'I-485', 'I-912', 'I-765'], '[]'::jsonb, '[{"id":"under_21","question":"¿El menor tiene menos de 21 años?","type":"boolean","required_answer":true,"fail_message":"Debe ser menor de 21 años."},{"id":"unmarried","question":"¿El menor está soltero/a?","type":"boolean","required_answer":true,"fail_message":"Debe estar soltero/a."},{"id":"abuse_neglect","question":"¿El menor ha sido víctima de abuso, negligencia o abandono?","type":"boolean","required_answer":true,"fail_message":"SIJS requiere determinación de abuso, negligencia o abandono."},{"id":"in_us","question":"¿El menor está actualmente en Estados Unidos?","type":"boolean","required_answer":true}]'::jsonb, 'Baby', 3),

('Cambio de Corte', 'cambio-de-corte', 'Transferir su caso de inmigración a una corte en otra ciudad o estado.', 1500.00, true, 6, 30, '2-4 meses', ARRAY['Motion to Change Venue'], '[]'::jsonb, NULL, 'ArrowRightLeft', 4),

('Declaración de Impuestos', 'taxes', 'Preparación y presentación de su declaración de impuestos ante el IRS.', 250.00, false, 1, 100, '2-4 semanas', ARRAY['1040', '1040-NR'], '[]'::jsonb, NULL, 'Receipt', 5),

('Número ITIN', 'itin-number', 'Solicitud de número de identificación tributaria individual ante el IRS.', 350.00, false, 1, 100, '7-11 semanas', ARRAY['W-7', '1040'], '[]'::jsonb, NULL, 'Hash', 6),

('Ajuste de Estatus', 'ajuste-de-estatus', 'Solicitud de residencia permanente (Green Card) para personas dentro de EE.UU.', 5500.00, true, 12, 20, '8-36 meses', ARRAY['I-485', 'I-130', 'I-864', 'I-765', 'I-131', 'I-693'], '[]'::jsonb, '[{"id":"in_us","question":"¿Está físicamente en Estados Unidos?","type":"boolean","required_answer":true},{"id":"basis","question":"¿Cuál es la base para su Green Card?","type":"select","options":["Matrimonio con ciudadano/a","Matrimonio con residente permanente","Hijo/a de ciudadano/a","Padre/madre de ciudadano/a","Empleo","Asilo aprobado","SIJS aprobado","Otro"],"required":true}]'::jsonb, 'CreditCard', 7),

('Mociones', 'mociones', 'Mociones ante Corte de Inmigración para reabrir, reconsiderar o apelar decisiones.', 2000.00, true, 6, 30, '3-12 meses', ARRAY['Motion to Reopen', 'Motion to Reconsider', 'EOIR-26'], '[]'::jsonb, NULL, 'FileText', 8),

('Licencia de Conducir', 'licencia-de-conducir', 'Asistencia con la solicitud de licencia de conducir estatal.', 300.00, false, 1, 100, '2-6 semanas', ARRAY['Formulario estatal DMV'], '[]'::jsonb, NULL, 'Car', 9);
